version: '3.8'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: dokoon_db
      POSTGRES_USER: dokoon_user
      POSTGRES_PASSWORD: dokoon_password

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgres://dokoon_user:dokoon_password@db:5432/dokoon_db
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
    ports:
      - "5000:5000"
    depends_on:
      - backend

volumes:
  postgres_data:
